apiVersion: v1
kind: Service
metadata:
  name: profile-db
  namespace: default
  labels:
    app: profile-db
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: profile-db
  ports:
  -
    port: 9042
    targetPort: cql
