apiVersion: v1
kind: Service
metadata:
  name: profile-db-local
  namespace: default
  labels:
    app: profile-db
spec:
  type: NodePort
  selector:
    app: profile-db
  ports:
  -
    port: 9042
    targetPort: cql
